// angular-app/src/app/core/layout/main-layout.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-main-layout',
  template: `
    <div class="min-h-screen bg-background">
      <app-sidebar></app-sidebar>
      <main class="ml-64 min-h-screen">
        <ng-content></ng-content>
      </main>
    </div>
  `
})
export class MainLayoutComponent {}

// frontend/src/components/layout/MainLayout.tsx
import { Sidebar } from "./Sidebar";

interface MainLayoutProps {
  children: React.ReactNode;
}

export function MainLayout({ children }: MainLayoutProps) {
  return (
    <div className="min-h-screen bg-background">
      <Sidebar />
      <main className="ml-64 min-h-screen">
        {children}
      </main>
    </div>
  );
}
