// frontend/src/pages/Login.tsx

import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardDescription, CardFooter, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { toast } from "sonner";
import { Loader2 } from "lucide-react";

export default function Login() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [loading, setLoading] = useState(false);
  const navigate = useNavigate();

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const { error } = await supabase.auth.signInWithPassword({
        email,
        password,
      });

      if (error) throw error;

      toast.success("Welcome back!");
      navigate("/chat");
    } catch (error: any) {
      toast.error(error.message || "Failed to sign in");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen flex items-center justify-center bg-gray-50 p-4">
      <Card className="w-full max-w-md">
        <CardHeader>
          <CardTitle>Welcome Back</CardTitle>
          <CardDescription>Sign in to your account to continue</CardDescription>
        </CardHeader>
        <form onSubmit={handleLogin}>
          <CardContent className="space-y-4">
            <div className="space-y-2">
              <Label htmlFor="email">Email</Label>
              <Input
                id="email"
                type="email"
                placeholder="m@example.com"
                value={email}
                onChange={(e) => setEmail(e.target.value)}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="password">Password</Label>
              <Input
                id="password"
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                required
              />
            </div>
          </CardContent>
          <CardFooter className="flex flex-col space-y-4">
            <Button type="submit" className="w-full" disabled={loading}>
              {loading && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Sign In
            </Button>
            <div className="text-center text-sm text-muted-foreground">
              Don't have an account?{" "}
              <Link to="/signup" className="text-primary hover:underline">
                Sign up
              </Link>
            </div>
          </CardFooter>
        </form>
      </Card>
    </div>
  );
}

// angular-app/src/app/features/auth/login/login.component.ts
import { Component } from '@angular/core';
import { FormBuilder, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { toast } from 'ngx-sonner';

@Component({
  selector: 'app-login',
  template: `
    <div class="min-h-screen flex items-center justify-center bg-gray-50 p-4">
      <app-card class="w-full max-w-md">
        <app-card-header>
          <app-card-title>Welcome Back</app-card-title>
          <app-card-description>Sign in to your account to continue</app-card-description>
        </app-card-header>
        <form [formGroup]="loginForm" (ngSubmit)="handleLogin()">
          <app-card-content class="space-y-4">
            <div class="space-y-2">
              <label appLabel for="email">Email</label>
              <input appInput id="email" type="email" placeholder="m@example.com" formControlName="email" required />
            </div>
            <div class="space-y-2">
              <label appLabel for="password">Password</label>
              <input appInput id="password" type="password" formControlName="password" required />
            </div>
          </app-card-content>
          <app-card-footer class="flex flex-col space-y-4">
            <button appButton type="submit" class="w-full" [disabled]="loading">
              <lucide-icon *ngIf="loading" name="loader-2" class="mr-2 h-4 w-4 animate-spin"></lucide-icon>
              Sign In
            </button>
            <div class="text-center text-sm text-muted-foreground">
              Don't have an account? 
              <a routerLink="/signup" class="text-primary hover:underline">
                Sign up
              </a>
            </div>
          </app-card-footer>
        </form>
      </app-card>
    </div>
  `
})
export class LoginComponent {
  loginForm = this.fb.group({
    email: ['', [Validators.required, Validators.email]],
    password: ['', Validators.required]
  });
  loading = false;

  constructor(
    private fb: FormBuilder,
    private authService: AuthService,
    private router: Router
  ) {}

  async handleLogin() {
    if (this.loginForm.invalid) return;
    
    this.loading = true;
    const { email, password } = this.loginForm.value;
    
    try {
      const { error } = await this.authService.signInWithPassword(email!, password!);
      if (error) throw error;
      
      toast.success("Welcome back!");
      this.router.navigate(['/chat']);
    } catch (error: any) {
      toast.error(error.message || "Failed to sign in");
    } finally {
      this.loading = false;
    }
  }
}
