// frontend/src/components/chat/ChatInput.tsx
import { useState, KeyboardEvent } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Send, Paperclip, Smile } from "lucide-react";
import { motion } from "framer-motion";

interface ChatInputProps {
  onSend: (message: string) => void;
  disabled?: boolean;
  placeholder?: string;
}

export function ChatInput({ onSend, disabled, placeholder = "Type your message..." }: ChatInputProps) {
  const [message, setMessage] = useState("");

  const handleSend = () => {
    if (message.trim() && !disabled) {
      onSend(message.trim());
      setMessage("");
    }
  };

  const handleKeyDown = (e: KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="p-4 border-t border-border bg-card/80 backdrop-blur-lg"
    >
      <div className="flex items-end gap-3">
        <div className="flex-1 relative">
          <Textarea
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder={placeholder}
            disabled={disabled}
            className="min-h-[48px] max-h-[200px] resize-none pr-24 bg-secondary/50 border-border/50 focus:border-accent/50 focus:ring-accent/20 rounded-xl"
            rows={1}
          />
          <div className="absolute right-2 bottom-2 flex items-center gap-1">
            <Button
              type="button"
              variant="ghost"
              size="icon-sm"
              className="text-muted-foreground hover:text-foreground"
            >
              <Paperclip className="w-4 h-4" />
            </Button>
            <Button
              type="button"
              variant="ghost"
              size="icon-sm"
              className="text-muted-foreground hover:text-foreground"
            >
              <Smile className="w-4 h-4" />
            </Button>
          </div>
        </div>
        <Button
          onClick={handleSend}
          disabled={!message.trim() || disabled}
          variant="accent"
          size="icon"
          className="rounded-xl"
        >
          <Send className="w-4 h-4" />
        </Button>
      </div>
      <p className="text-[10px] text-muted-foreground text-center mt-2">
        Press Enter to send • Shift + Enter for new line
      </p>
    </motion.div>
  );
}

// angular-app/src/app/features/chat/components/chat-input.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Send, Mic, Paperclip } from 'lucide-angular';

@Component({
  selector: 'app-chat-input',
  template: `
    <div class="p-4 bg-card/50 backdrop-blur-sm border-t border-border">
      <div class="relative flex items-end gap-2">
        <button appButton variant="ghost" size="icon" class="text-muted-foreground hover:text-foreground shrink-0">
          <lucide-icon [name]="Paperclip" class="w-5 h-5"></lucide-icon>
        </button>
        
        <div class="relative flex-1">
          <textarea
            appInput
            rows="1"
            placeholder="Type your message..."
            class="min-h-[44px] max-h-32 py-3 pr-12 resize-none"
            [(ngModel)]="message"
            (keydown.enter)="handleKeyDown($event)"
            [disabled]="disabled"
          ></textarea>
          <button 
            appButton
            size="icon-sm"
            [variant]="message.trim() ? 'default' : 'ghost'"
            class="absolute right-1.5 bottom-1.5 transition-all duration-200"
            [disabled]="!message.trim() || disabled"
            (click)="handleSend()"
          >
            <lucide-icon [name]="Send" class="w-4 h-4"></lucide-icon>
          </button>
        </div>

        <button appButton variant="ghost" size="icon" class="text-muted-foreground hover:text-foreground shrink-0">
          <lucide-icon [name]="Mic" class="w-5 h-5"></lucide-icon>
        </button>
      </div>
      <div class="mt-2 text-center">
        <p class="text-[10px] text-muted-foreground">
          AI can make mistakes. Please verify important information.
        </p>
      </div>
    </div>
  `
})
export class ChatInputComponent {
  @Input() disabled = false;
  @Output() onSend = new EventEmitter<string>();

  message = "";
  readonly Send = Send;
  readonly Mic = Mic;
  readonly Paperclip = Paperclip;

  handleSend() {
    if (this.message.trim() && !this.disabled) {
      this.onSend.emit(this.message.trim());
      this.message = "";
    }
  }

  handleKeyDown(event: Event) {
    const e = event as KeyboardEvent;
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      this.handleSend();
    }
  }
}
