// frontend/src/pages/Conversations.tsx
import { MainLayout } from "@/components/layout/MainLayout";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { 
  Search, 
  Filter,
  MessageSquare,
  Clock,
  Star,
  MoreVertical
} from "lucide-react";
import { motion } from "framer-motion";
import { useState } from "react";

import { useQuery } from "@tanstack/react-query";
import { supabase } from "@/integrations/supabase/client";
import { formatDistanceToNow } from "date-fns";

export default function ConversationsPage() {
  const [searchQuery, setSearchQuery] = useState("");
  const [filter, setFilter] = useState<"all" | "resolved" | "pending" | "escalated">("all");

  const { data: conversations = [], isLoading } = useQuery({
    queryKey: ["conversations"],
    queryFn: async () => {
      const { data, error } = await supabase
        .from("conversations")
        .select(`
          id,
          status,
          avg_confidence,
          sentiment,
          updated_at,
          user_profiles (
            display_name,
            email
          ),
          messages (
            content,
            created_at,
            role
          )
        `)
        .order("updated_at", { ascending: false });

      if (error) throw error;

      return data.map((conv: any) => {
        const profile = Array.isArray(conv.user_profiles)
          ? conv.user_profiles[0]
          : conv.user_profiles;

        const userName =
          profile?.display_name ||
          profile?.email ||
          "Guest User";
          
        const userEmail = profile?.email || "";

        // Get last message logic
        const messages = conv.messages || [];
        // Sort by created_at desc to find latest
        const sortedMessages = [...messages].sort(
            (a: any, b: any) => new Date(b.created_at).getTime() - new Date(a.created_at).getTime()
        );
        const lastMessage = sortedMessages[0]?.content || "No messages";

        return {
          id: conv.id,
          user: userName,
          email: userEmail,
          lastMessage: lastMessage,
          status: conv.status,
          confidence: conv.avg_confidence || 0,
          sentiment: conv.sentiment || "neutral",
          messages: messages.length,
          duration: formatDistanceToNow(new Date(conv.updated_at), { addSuffix: true }),
          time: new Date(conv.updated_at).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }),
          rating: conv.rating, 
        };
      });
    }
  });

  const filteredConversations = conversations.filter(conv => {
    const matchesSearch = conv.user.toLowerCase().includes(searchQuery.toLowerCase()) ||
      conv.lastMessage.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesFilter = filter === "all" || conv.status === filter;
    return matchesSearch && matchesFilter;
  });

  return (
    <MainLayout>
      <div className="p-6 space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-2xl font-bold">Conversations</h1>
            <p className="text-muted-foreground">All customer interactions</p>
          </div>
          <div className="flex gap-2">
            <Badge variant="resolved" className="px-3 py-1">
              {conversations.filter(c => c.status === "resolved").length} Resolved
            </Badge>
            <Badge variant="pending" className="px-3 py-1">
              {conversations.filter(c => c.status === "pending").length} Pending
            </Badge>
            <Badge variant="escalated" className="px-3 py-1">
              {conversations.filter(c => c.status === "escalated").length} Escalated
            </Badge>
          </div>
        </div>

        {/* Search and Filter */}
        <div className="flex gap-4">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" />
            <Input
              placeholder="Search conversations..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              className="pl-10"
            />
          </div>
          <div className="flex gap-2">
            {(["all", "resolved", "pending", "escalated"] as const).map(f => (
              <Button
                key={f}
                variant={filter === f ? "accent" : "outline"}
                size="sm"
                onClick={() => setFilter(f)}
                className="capitalize"
              >
                {f}
              </Button>
            ))}
          </div>
        </div>

        {/* Conversations List */}
        <Card className="glass-card">
          <CardContent className="p-0">
            <div className="divide-y divide-border">
              {filteredConversations.map((conv, index) => (
                <motion.div
                  key={conv.id}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ delay: index * 0.05 }}
                  className="p-4 hover:bg-secondary/30 transition-colors cursor-pointer flex items-center gap-4"
                >
                  {/* Avatar */}
                  <div className={`w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ${
                    conv.sentiment === "positive" ? "bg-success/20" :
                    conv.sentiment === "negative" ? "bg-destructive/20" : "bg-secondary"
                  }`}>
                    <span className={`text-sm font-medium ${
                      conv.sentiment === "positive" ? "text-success" :
                      conv.sentiment === "negative" ? "text-destructive" : "text-muted-foreground"
                    }`}>
                      {conv.user.split(" ").map(n => n[0]).join("")}
                    </span>
                  </div>

                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="font-medium text-sm">{conv.user}</h3>
                      <Badge 
                        variant={conv.status as any}
                        className="text-[10px]"
                      >
                        {conv.status}
                      </Badge>
                    </div>
                    <p className="text-sm text-muted-foreground truncate">{conv.lastMessage}</p>
                    <div className="flex items-center gap-4 mt-1.5 text-xs text-muted-foreground">
                      <span className="flex items-center gap-1">
                        <MessageSquare className="w-3 h-3" />
                        {conv.messages} messages
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock className="w-3 h-3" />
                        {conv.duration}
                      </span>
                      {conv.rating && (
                        <span className="flex items-center gap-1">
                          <Star className="w-3 h-3 text-warning fill-warning" />
                          {conv.rating}/5
                        </span>
                      )}
                    </div>
                  </div>

                  {/* Stats */}
                  <div className="text-right flex-shrink-0">
                    <p className={`text-lg font-bold ${
                      conv.confidence >= 0.85 ? "text-success" :
                      conv.confidence >= 0.6 ? "text-warning" : "text-destructive"
                    }`}>
                      {Math.round(conv.confidence * 100)}%
                    </p>
                    <p className="text-xs text-muted-foreground">{conv.time}</p>
                  </div>

                  {/* Actions */}
                  <Button variant="ghost" size="icon-sm" className="flex-shrink-0">
                    <MoreVertical className="w-4 h-4" />
                  </Button>
                </motion.div>
              ))}
            </div>
          </CardContent>
        </Card>
      </div>
    </MainLayout>
  );
}

// angular-app/src/app/features/conversations/conversations.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { UiModule } from '../../shared/ui/ui.module';
import { LucideAngularModule } from 'lucide-angular';
import { CoreModule } from '../../core/core.module';
import { trigger, transition, style, animate } from '@angular/animations';

interface Conversation {
  id: number;
  user: string;
  email: string;
  lastMessage: string;
  status: 'resolved' | 'pending' | 'escalated';
  confidence: number;
  sentiment: 'positive' | 'neutral' | 'negative';
  messages: number;
  duration: string;
  time: string;
  rating: number | null;
}

@Component({
  selector: 'app-conversations',
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    UiModule,
    LucideAngularModule,
    CoreModule
  ],
  template: `
    <app-main-layout>
      <div class="p-6 space-y-6">
        <!-- Header -->
        <div class="flex items-center justify-between">
          <div>
            <h1 class="text-2xl font-bold">Conversations</h1>
            <p class="text-muted-foreground">All customer interactions</p>
          </div>
          <div class="flex gap-2">
            <span appBadge variant="resolved" class="px-3 py-1">
              {{ getStatusCount('resolved') }} Resolved
            </span>
            <span appBadge variant="pending" class="px-3 py-1">
              {{ getStatusCount('pending') }} Pending
            </span>
            <span appBadge variant="escalated" class="px-3 py-1">
              {{ getStatusCount('escalated') }} Escalated
            </span>
          </div>
        </div>

        <!-- Search and Filter -->
        <div class="flex gap-4">
          <div class="relative flex-1">
            <lucide-icon name="search" class="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground"></lucide-icon>
            <input
              appInput
              placeholder="Search conversations..."
              [(ngModel)]="searchQuery"
              class="pl-10"
            />
          </div>
          <div class="flex gap-2">
            <button
              *ngFor="let f of filters"
              appButton
              [variant]="filter === f ? 'accent' : 'outline'"
              size="sm"
              (click)="filter = f"
              class="capitalize"
            >
              {{ f }}
            </button>
          </div>
        </div>

        <!-- Conversations List -->
        <app-card class="glass-card">
          <app-card-content class="p-0">
            <div class="divide-y divide-border">
              <div
                *ngFor="let conv of filteredConversations; let i = index"
                [@fadeIn]="{ value: 'in', params: { delay: i * 50 } }"
                class="p-4 hover:bg-secondary/30 transition-colors cursor-pointer flex items-center gap-4"
              >
                <!-- Avatar -->
                <div [class]="'w-10 h-10 rounded-full flex items-center justify-center flex-shrink-0 ' + getSentimentBg(conv.sentiment)">
                  <span [class]="'text-sm font-medium ' + getSentimentText(conv.sentiment)">
                    {{ getInitials(conv.user) }}
                  </span>
                </div>

                <!-- Content -->
                <div class="flex-1 min-w-0">
                  <div class="flex items-center gap-2 mb-1">
                    <h3 class="font-medium text-sm">{{ conv.user }}</h3>
                    <span appBadge [variant]="conv.status" class="text-[10px]">
                      {{ conv.status }}
                    </span>
                  </div>
                  <p class="text-sm text-muted-foreground truncate">{{ conv.lastMessage }}</p>
                  <div class="flex items-center gap-4 mt-1.5 text-xs text-muted-foreground">
                    <span class="flex items-center gap-1">
                      <lucide-icon name="message-square" class="w-3 h-3"></lucide-icon>
                      {{ conv.messages }} messages
                    </span>
                    <span class="flex items-center gap-1">
                      <lucide-icon name="clock" class="w-3 h-3"></lucide-icon>
                      {{ conv.duration }}
                    </span>
                    <span *ngIf="conv.rating" class="flex items-center gap-1">
                      <lucide-icon name="star" class="w-3 h-3 text-warning fill-warning"></lucide-icon>
                      {{ conv.rating }}/5
                    </span>
                  </div>
                </div>

                <!-- Stats -->
                <div class="text-right flex-shrink-0">
                  <p [class]="'text-lg font-bold ' + getConfidenceColor(conv.confidence)">
                    {{ Math.round(conv.confidence * 100) }}%
                  </p>
                  <p class="text-xs text-muted-foreground">{{ conv.time }}</p>
                </div>

                <!-- Actions -->
                <button appButton variant="ghost" size="icon-sm" class="flex-shrink-0">
                  <lucide-icon name="more-vertical" class="w-4 h-4"></lucide-icon>
                </button>
              </div>
            </div>
          </app-card-content>
        </app-card>
      </div>
    </app-main-layout>
  `,
  animations: [
    trigger('fadeIn', [
      transition(':enter', [
        style({ opacity: 0 }),
        animate('300ms {{ delay }}ms ease-out', style({ opacity: 1 }))
      ], { params: { delay: 0 } })
    ])
  ]
})
export class ConversationsComponent {
  searchQuery = '';
  filter: 'all' | 'resolved' | 'pending' | 'escalated' = 'all';
  filters: ('all' | 'resolved' | 'pending' | 'escalated')[] = ['all', 'resolved', 'pending', 'escalated'];
  Math = Math; // Make Math available in template

  conversations: Conversation[] = [
    {
      id: 1,
      user: "Sarah Martinez",
      email: "sarah.m@example.com",
      lastMessage: "Thank you! That solved my problem.",
      status: "resolved",
      confidence: 0.94,
      sentiment: "positive",
      messages: 8,
      duration: "4 min",
      time: "10:42 AM",
      rating: 5,
    },
    {
      id: 2,
      user: "John Davis",
      email: "john.d@example.com",
      lastMessage: "I need more information about the enterprise plan",
      status: "pending",
      confidence: 0.78,
      sentiment: "neutral",
      messages: 5,
      duration: "7 min",
      time: "10:38 AM",
      rating: null,
    },
    {
      id: 3,
      user: "Emma Wilson",
      email: "emma.w@example.com",
      lastMessage: "This is ridiculous! Nothing works!",
      status: "escalated",
      confidence: 0.42,
      sentiment: "negative",
      messages: 12,
      duration: "15 min",
      time: "10:25 AM",
      rating: 1,
    },
    {
      id: 4,
      user: "Michael Brown",
      email: "m.brown@example.com",
      lastMessage: "Perfect, I understand now. Thanks!",
      status: "resolved",
      confidence: 0.91,
      sentiment: "positive",
      messages: 6,
      duration: "3 min",
      time: "10:15 AM",
      rating: 5,
    },
    {
      id: 5,
      user: "Lisa Johnson",
      email: "lisa.j@example.com",
      lastMessage: "Can you help me with API integration?",
      status: "pending",
      confidence: 0.67,
      sentiment: "neutral",
      messages: 4,
      duration: "6 min",
      time: "10:08 AM",
      rating: null,
    },
    {
      id: 6,
      user: "Robert Kim",
      email: "r.kim@example.com",
      lastMessage: "Got it working! The documentation helped.",
      status: "resolved",
      confidence: 0.88,
      sentiment: "positive",
      messages: 10,
      duration: "8 min",
      time: "9:55 AM",
      rating: 4,
    },
  ];

  get filteredConversations() {
    return this.conversations.filter(conv => {
      const matchesSearch = conv.user.toLowerCase().includes(this.searchQuery.toLowerCase()) ||
        conv.lastMessage.toLowerCase().includes(this.searchQuery.toLowerCase());
      const matchesFilter = this.filter === 'all' || conv.status === this.filter;
      return matchesSearch && matchesFilter;
    });
  }

  getStatusCount(status: string) {
    return this.conversations.filter(c => c.status === status).length;
  }

  getInitials(name: string) {
    return name.split(" ").map(n => n[0]).join("");
  }

  getSentimentBg(sentiment: string) {
    if (sentiment === 'positive') return 'bg-success/20';
    if (sentiment === 'negative') return 'bg-destructive/20';
    return 'bg-muted';
  }

  getSentimentText(sentiment: string) {
    if (sentiment === 'positive') return 'text-success';
    if (sentiment === 'negative') return 'text-destructive';
    return 'text-muted-foreground';
  }

  getConfidenceColor(confidence: number) {
    if (confidence >= 0.85) return 'text-success';
    if (confidence >= 0.6) return 'text-warning';
    return 'text-destructive';
  }
}
